export interface EmojiEntry {
  emoji: string;
  keywords: string;
}

export const EMOJIS: EmojiEntry[] = [
  { emoji: "😂", keywords: "lachen haha lol laugh laughing" },
  { emoji: "😅", keywords: "schweiss nervoes sweat nervous" },
  { emoji: "😉", keywords: "zwinkern wink" },
  { emoji: "😍", keywords: "herzaugen liebe heart eyes love" },
  { emoji: "🥳", keywords: "party feiern celebrate" },
  { emoji: "😱", keywords: "schock schreck shock scream" },
  { emoji: "😭", keywords: "weinen traurig cry sad" },
  { emoji: "🤔", keywords: "nachdenken hmm think thinking" },
  { emoji: "🙄", keywords: "augenrollen eyeroll" },
  { emoji: "😴", keywords: "schlafen muede sleep tired" },
  { emoji: "🤯", keywords: "kopf explodiert wow mind blown" },
  { emoji: "🥵", keywords: "heiss stress hot" },
  { emoji: "🥶", keywords: "kalt cold" },
  { emoji: "😈", keywords: "teufel fies devil evil" },
  { emoji: "🤡", keywords: "clown quatsch clown nonsense" },
  { emoji: "💩", keywords: "kacke mist poop crap" },
  { emoji: "👻", keywords: "geist gruselig ghost spooky" },
  { emoji: "👽", keywords: "alien ausserirdisch alien" },
  { emoji: "🤖", keywords: "roboter robot" },
  { emoji: "👍", keywords: "daumen hoch super gut thumbs up good" },
  { emoji: "👎", keywords: "daumen runter schlecht thumbs down bad" },
  { emoji: "👏", keywords: "applaus klatschen applause clap" },
  { emoji: "🙌", keywords: "yeah gefeiert yeah cheer" },
  { emoji: "🤝", keywords: "handschlag deal handshake" },
  { emoji: "🖕", keywords: "stinkefinger middle finger" },
  { emoji: "✌️", keywords: "peace" },
  { emoji: "🤞", keywords: "daumen druecken fingers crossed" },
  { emoji: "👌", keywords: "ok perfekt ok perfect" },
  { emoji: "🫡", keywords: "salutieren respekt salute respect" },
  { emoji: "🎉", keywords: "konfetti party feier confetti celebration" },
  { emoji: "🔥", keywords: "feuer geil hot fire" },
  { emoji: "💯", keywords: "hundert perfekt hundred perfect" },
  { emoji: "⭐", keywords: "stern super star" },
  { emoji: "✨", keywords: "glitzer magie sparkle magic" },
  { emoji: "💥", keywords: "bumm explosion boom" },
  { emoji: "❤️", keywords: "herz liebe heart love" },
  { emoji: "💔", keywords: "gebrochenes herz broken heart" },
  { emoji: "🍅", keywords: "tomate wurf tomato throw" },
  { emoji: "🥚", keywords: "ei wurf egg throw" },
  { emoji: "🍕", keywords: "pizza essen pizza food" },
  { emoji: "🍺", keywords: "bier prost beer cheers" },
  { emoji: "☕", keywords: "kaffee pause coffee break" },
  { emoji: "🍿", keywords: "popcorn drama popcorn" },
  { emoji: "🐌", keywords: "schnecke langsam snail slow" },
  { emoji: "🐢", keywords: "schildkroete langsam turtle slow" },
  { emoji: "🐒", keywords: "affe quatsch monkey nonsense" },
  { emoji: "🦥", keywords: "faultier faul langsam sloth lazy slow" },
  { emoji: "🐛", keywords: "bug fehler bug error" },
  { emoji: "🐍", keywords: "schlange python snake" },
  { emoji: "🚀", keywords: "rakete schnell deploy rocket fast" },
  { emoji: "🛠️", keywords: "werkzeug fixen tools fix" },
  { emoji: "🐞", keywords: "bug kaefer fehler bug beetle error" },
  { emoji: "💣", keywords: "bombe kritisch bomb critical" },
  { emoji: "⏰", keywords: "wecker zeit deadline alarm time" },
  { emoji: "🧠", keywords: "hirn denken brain think" },
  { emoji: "🙏", keywords: "bitte danke please thanks" },
  { emoji: "😬", keywords: "peinlich autsch awkward oops" },
  { emoji: "🫠", keywords: "schmelzen zerfliessen melting" },
  { emoji: "🤌", keywords: "moment kuss italienisch chef's kiss" },
  { emoji: "🥲", keywords: "traenen laecheln tears smile" },
];
