export interface EmojiEntry {
  emoji: string;
  keywords: string;
}

export const EMOJIS: EmojiEntry[] = [
  { emoji: "😂", keywords: "lachen haha lol" },
  { emoji: "😅", keywords: "schweiss nervoes" },
  { emoji: "😉", keywords: "zwinkern" },
  { emoji: "😍", keywords: "herzaugen liebe" },
  { emoji: "🥳", keywords: "party feiern" },
  { emoji: "😱", keywords: "schock schreck" },
  { emoji: "😭", keywords: "weinen traurig" },
  { emoji: "🤔", keywords: "nachdenken hmm" },
  { emoji: "🙄", keywords: "augenrollen" },
  { emoji: "😴", keywords: "schlafen muede" },
  { emoji: "🤯", keywords: "kopf explodiert wow" },
  { emoji: "🥵", keywords: "heiss stress" },
  { emoji: "🥶", keywords: "kalt" },
  { emoji: "😈", keywords: "teufel fies" },
  { emoji: "🤡", keywords: "clown quatsch" },
  { emoji: "💩", keywords: "kacke mist" },
  { emoji: "👻", keywords: "geist gruselig" },
  { emoji: "👽", keywords: "alien ausserirdisch" },
  { emoji: "🤖", keywords: "roboter" },
  { emoji: "👍", keywords: "daumen hoch super gut" },
  { emoji: "👎", keywords: "daumen runter schlecht" },
  { emoji: "👏", keywords: "applaus klatschen" },
  { emoji: "🙌", keywords: "yeah gefeiert" },
  { emoji: "🤝", keywords: "handschlag deal" },
  { emoji: "🖕", keywords: "stinkefinger" },
  { emoji: "✌️", keywords: "peace" },
  { emoji: "🤞", keywords: "daumen druecken" },
  { emoji: "👌", keywords: "ok perfekt" },
  { emoji: "🫡", keywords: "salutieren respekt" },
  { emoji: "🎉", keywords: "konfetti party feier" },
  { emoji: "🔥", keywords: "feuer geil hot" },
  { emoji: "💯", keywords: "hundert perfekt" },
  { emoji: "⭐", keywords: "stern super" },
  { emoji: "✨", keywords: "glitzer magie" },
  { emoji: "💥", keywords: "bumm explosion" },
  { emoji: "❤️", keywords: "herz liebe" },
  { emoji: "💔", keywords: "gebrochenes herz" },
  { emoji: "🍅", keywords: "tomate wurf" },
  { emoji: "🥚", keywords: "ei wurf" },
  { emoji: "🍕", keywords: "pizza essen" },
  { emoji: "🍺", keywords: "bier prost" },
  { emoji: "☕", keywords: "kaffee pause" },
  { emoji: "🍿", keywords: "popcorn drama" },
  { emoji: "🐌", keywords: "schnecke langsam" },
  { emoji: "🐢", keywords: "schildkroete langsam" },
  { emoji: "🐒", keywords: "affe quatsch" },
  { emoji: "🦥", keywords: "faultier faul langsam" },
  { emoji: "🐛", keywords: "bug fehler" },
  { emoji: "🐍", keywords: "schlange python" },
  { emoji: "🚀", keywords: "rakete schnell deploy" },
  { emoji: "🛠️", keywords: "werkzeug fixen" },
  { emoji: "🐞", keywords: "bug kaefer fehler" },
  { emoji: "💣", keywords: "bombe kritisch" },
  { emoji: "⏰", keywords: "wecker zeit deadline" },
  { emoji: "🧠", keywords: "hirn denken" },
  { emoji: "🙏", keywords: "bitte danke" },
  { emoji: "😬", keywords: "peinlich autsch" },
  { emoji: "🫠", keywords: "schmelzen zerfliessen" },
  { emoji: "🤌", keywords: "moment kuss italienisch" },
  { emoji: "🥲", keywords: "traenen laecheln" },
];
